
The repo hash for this run is: 04842a5

The branch on which it was run: pic_michael


::: Setting up enviroment for Intel oneAPI 2022 (ifort-classic)

::::::::::::::::::::::::: blast [ramses/hlld_eos] :::::::::::::::::::::::::
::: Compilation

::::::::::::::::::::::::: rt_shadow [ramses/hlls] :::::::::::::::::::::::::
::: Compilation

:::::::::::::::::: stellar_atmospheres [ramses/hlld_eos] ::::::::::::::::::
::: Compilation
::: Running single step (1x MPI 4x OpenMP)
Traceback (most recent call last):
  File "utilities/python/bifrost_test.py", line 256, in <module>
    main()
  File "/mn/stornext/u3/miko/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mn/stornext/u3/miko/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mn/stornext/u3/miko/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mn/stornext/u3/miko/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "utilities/python/bifrost_test.py", line 170, in main
    res = subprocess.run(f"{s.setup}{unit.run}",
  File "/mn/stornext/u3/miko/anaconda3/lib/python3.8/subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/mn/stornext/u3/miko/anaconda3/lib/python3.8/subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/mn/stornext/u3/miko/anaconda3/lib/python3.8/subprocess.py", line 1908, in _communicate
    stderr = self._translate_newlines(stderr,
  File "/mn/stornext/u3/miko/anaconda3/lib/python3.8/subprocess.py", line 901, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1739: invalid start byte
