
The repo hash for this run is: 6ab3bbcb3

The branch on which it was run: pic_michael


::: Setting up enviroment for Intel oneAPI 2022 (ifort-classic)

::::::::::::::::::::::::: blast [ramses/hlld_eos] :::::::::::::::::::::::::
::: Compilation

::::::::::::::::::::::::: rt_shadow [ramses/hlls] :::::::::::::::::::::::::
::: Compilation

:::::::::::::::::: stellar_atmospheres [ramses/hlld_eos] ::::::::::::::::::
::: Compilation
::: Running single step (1x MPI 4x OpenMP)
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Dispatch-Bifrost_pic_michael/utilities/python/bifrost_test.py", line 256, in <module>
    main()
  File "/mn/stornext/u3/miko/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/mn/stornext/u3/miko/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/mn/stornext/u3/miko/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mn/stornext/u3/miko/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/var/lib/jenkins/workspace/Dispatch-Bifrost_pic_michael/utilities/python/bifrost_test.py", line 170, in main
    res = subprocess.run(f"{s.setup}{unit.run}",
  File "/usr/lib64/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib64/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.9/subprocess.py", line 2021, in _communicate
    stderr = self._translate_newlines(stderr,
  File "/usr/lib64/python3.9/subprocess.py", line 1011, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 1785: invalid continuation byte
